name: Build macOS dylib

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile dylib
      run: |
        clang -dynamiclib -framework Cocoa HiWindow.m -o libhi.dylib

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hi-dylib
        path: libhi.dylib
